#!/bin/sh

suspend="n"
cmd="tomcat7:run"

for var in "$@"
do
	if [ $var = "wait" ]; then
		suspend="y"
	elif [ $var = "war" ]; then
		cmd="tomcat7:run-war"
	else
		export PREODAY_DBNAME=$var
	fi
done

# Run tomcat in debug mode
MAVEN_DEBUG_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=$suspend,address=8000"
export MAVEN_OPTS="$MAVEN_DEBUG_OPTS $MAVEN_OPTS"
mvn $cmd -DskipTests=true
#mvn jetty:run -DskipTests=true
